# Generated by Django 4.2.4 on 2023-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('github', models.URLField(blank=True)),
                ('other_link', models.URLField(blank=True)),
            ],
        ),
    ]
