# Generated by Django 4.2.4 on 2023-08-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='project_pics'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
