# Generated by Django 4.2.4 on 2023-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0002_project_image_project_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, verbose_name='Github Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='project_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_link',
            field=models.URLField(blank=True, verbose_name='Any Other Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Project'),
        ),
    ]
