# Generated by Django 4.2.4 on 2023-08-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0004_message_alter_cv_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(default='https://github.com/harsh098')),
                ('linkedin', models.URLField(default='https://https://www.linkedin.com/in/harsh-mishra-b94096144/')),
                ('twitter', models.URLField(default='https://twitter.com/harsh_dev8086')),
                ('facebook', models.URLField(default='https://www.facebook.com/')),
                ('discord', models.URLField(default='https://discordapp.com/users/776760813469958174')),
                ('instagram', models.URLField(default='https://instagram.com/harsh.dev8086')),
                ('location', models.CharField(default='Noida, India', max_length=255)),
                ('email', models.EmailField(default='hmisraji07@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('post', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=60)),
                ('ispresent', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
