# Generated by Django 4.2.4 on 2023-08-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0005_contactinfo_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='youtube',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(default=None),
        ),
    ]
