# Generated by Django 4.2.4 on 2023-08-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0006_contactinfo_youtube_alter_contactinfo_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='youtube',
            field=models.URLField(default=None, null=True),
        ),
    ]
