# Generated by Django 4.2.4 on 2023-08-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0008_alter_contactinfo_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
