# Generated by Django 4.2.4 on 2023-08-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0009_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
