# Generated by Django 4.2.4 on 2023-08-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreui', '0011_adcard_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='Harsh Mishra', max_length=128),
            preserve_default=False,
        ),
    ]
